version: '3.8'

services:
  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: chatbot-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - chatbot-network

  # Backend API
  backend:
    build: ./backend
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-this-in-production-12345
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - GEMINI_API_KEY=your-gemini-api-key-here
      - GEMINI_MODEL=gemini-2.0-flash
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin123
      - AWS_REGION=us-east-1
      - S3_BUCKET_NAME=chat-conversations
      - S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - minio
    networks:
      - chatbot-network

  # Frontend
  frontend:
    build: ./frontend
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - chatbot-network

volumes:
  minio_data:

networks:
  chatbot-network:
    driver: bridge